name: 'Automated Versioning and Tagging'
description:
  'It is designed to automate versioning and tagging for your repository'
author: 'Entech Solutions'

# Define your inputs here.
inputs:
  token:
    description: >
      Personal access token (PAT) used to manage tags of the repository.
    default: ${{ github.token }}
  majorVersion:
    description:
      'The major version of the release. The scripts changes only minor and
      patch versions.'
    default: '1'
  tagPrefix:
    description: 'The prefix of the tag to be created.'
    default: 'v'

# Define your outputs here.
outputs:
  version:
    description: 'Newly defined version'
  tag:
    description: 'Newly created tag'

runs:
  using: node20
  main: dist/index.js
