name: 'Automated Versioning and Tagging'
description:
  'It is designed to automate versioning and tagging for your repository'
author: 'Entech Solutions'

# Define your inputs here.
inputs:
  token:
    description: >
      Personal access token (PAT) used to manage tags of the repository.
    default: ${{ github.token }}
  majorVersion:
    description:
      'The major version of the release. The scripts changes only minor and
      patch versions.'
    default: '1'
  tagPrefix:
    description: 'The prefix of the tag to be created.'
    default: 'v'
  seekVersion:
    description:
      'Defines the version that should be found in the repository and returned
      in the format "major.minor.patch". If not set, the script will attempt to
      find the latest version in the repository and increment it.'
    default: ''

# Define your outputs here.
outputs:
  version:
    description: 'Version number in format "major.minor.patch"'
  tag:
    description: 'Tag name of the version'

runs:
  using: node20
  main: dist/index.js
